-- Supabase Schema Setup
--
-- This script creates the necessary tables, enables Row Level Security (RLS),
-- sets policies for public access, and creates a storage bucket.
--
-- Instructions:
-- 1. Navigate to the SQL Editor in your Supabase project dashboard.
-- 2. Copy the entire content of this file.
-- 3. Paste it into the SQL Editor and click "RUN".

-- 1. Create the 'contact_submissions' table
CREATE TABLE IF NOT EXISTS public.contact_submissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    name text NOT NULL,
    email text NOT NULL,
    company text,
    phone text,
    service text,
    budget text,
    message text NOT NULL,
    timeline text
);

-- 2. Create the 'internship_applications' table
-- Note: We use double quotes for column names that are camelCase to preserve case sensitivity,
-- matching the keys in the application's form data.
CREATE TABLE IF NOT EXISTS public.internship_applications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    name text NOT NULL,
    email text NOT NULL,
    phone text,
    dob date,
    gender text,
    "degreeProgram" text,
    university text,
    "yearOfStudy" text,
    "fieldOfInterest" text,
    skills text,
    experience text,
    "startDate" date,
    cv_url text,
    status text DEFAULT 'Pending'::text NOT NULL
);

-- 3. Create the 'cvs' storage bucket
-- We are making the bucket public to allow easy access to the CV URLs.
INSERT INTO storage.buckets (id, name, public)
VALUES ('cvs', 'cvs', true)
ON CONFLICT (id) DO NOTHING; -- This prevents an error if the bucket already exists.

-- 4. Set up Row Level Security (RLS) and Policies
-- This is a critical security step. By default, tables and storage are not accessible via the API.

-- Enable RLS for contact_submissions table
ALTER TABLE public.contact_submissions ENABLE ROW LEVEL SECURITY;

-- Create a policy to allow anonymous users to insert into contact_submissions
CREATE POLICY "Allow public insert for contact submissions"
ON public.contact_submissions
FOR INSERT
WITH CHECK (true);

-- Enable RLS for internship_applications table
ALTER TABLE public.internship_applications ENABLE ROW LEVEL SECURITY;

-- Create a policy to allow anonymous users to insert into internship_applications
CREATE POLICY "Allow public insert for internship applications"
ON public.internship_applications
FOR INSERT
WITH CHECK (true);

-- Create policies for the 'cvs' storage bucket
-- These policies allow your application to upload and read files from the bucket.
CREATE POLICY "Allow public read access to cvs bucket"
ON storage.objects FOR SELECT
USING ( bucket_id = 'cvs' );

CREATE POLICY "Allow anonymous uploads to cvs bucket"
ON storage.objects FOR INSERT
WITH CHECK ( bucket_id = 'cvs' );
