-- Contact submissions hardening + keepalive logs
-- Safe to run multiple times where possible

-- 1) Ensure contact_submissions table exists (for environments missing old setup)
CREATE TABLE IF NOT EXISTS public.contact_submissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    name text NOT NULL,
    email text NOT NULL,
    company text,
    phone text,
    service text,
    budget text,
    message text NOT NULL,
    timeline text
);

-- 2) Helpful indexes
CREATE INDEX IF NOT EXISTS idx_contact_submissions_created_at
    ON public.contact_submissions (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_contact_submissions_email
    ON public.contact_submissions (email);

-- 3) Keepalive logs table
CREATE TABLE IF NOT EXISTS public.db_keepalive_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    source text NOT NULL DEFAULT 'server',
    note text
);

CREATE INDEX IF NOT EXISTS idx_db_keepalive_logs_created_at
    ON public.db_keepalive_logs (created_at DESC);

-- 4) Enable RLS
ALTER TABLE public.contact_submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.db_keepalive_logs ENABLE ROW LEVEL SECURITY;

-- 5) Policies (drop/recreate for idempotency)
DROP POLICY IF EXISTS "Allow public insert for contact submissions" ON public.contact_submissions;
CREATE POLICY "Allow public insert for contact submissions"
ON public.contact_submissions
FOR INSERT
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow service role manage keepalive logs" ON public.db_keepalive_logs;
CREATE POLICY "Allow service role manage keepalive logs"
ON public.db_keepalive_logs
FOR ALL
USING (auth.role() = 'service_role')
WITH CHECK (auth.role() = 'service_role');
